# Generated by Django 4.1.3 on 2022-11-17 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=80)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=80)),
                ('dob', models.DateField()),
                ('address', models.TextField()),
                ('discipline', models.CharField(blank=True, max_length=50)),
                ('qualification', models.CharField(blank=True, max_length=50)),
                ('designation', models.CharField(max_length=20)),
                ('appointment_date', models.DateField()),
                ('appointment_type', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pupil_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('year_of_admission', models.PositiveIntegerField()),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.grade')),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.parent')),
            ],
        ),
        migrations.CreateModel(
            name='fee_third',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('academic_year', models.PositiveIntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('pupil_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pupil')),
            ],
        ),
        migrations.CreateModel(
            name='fee_second',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('academic_year', models.PositiveIntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('pupil_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pupil')),
            ],
        ),
        migrations.CreateModel(
            name='fee_first',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('academic_year', models.PositiveIntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('pupil_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pupil')),
            ],
        ),
    ]
