# Generated by Django 4.1.3 on 2022-11-18 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='fee_second',
            new_name='feeFirst',
        ),
        migrations.RenameModel(
            old_name='fee_first',
            new_name='feeSecond',
        ),
        migrations.RenameModel(
            old_name='fee_third',
            new_name='feeThird',
        ),
    ]
