# Generated by Django 4.1.3 on 2022-12-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_fee_second_feefirst_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='status',
            field=models.CharField(default='active', max_length=15),
        ),
    ]
